version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: mobility_postgres
    environment:
      POSTGRES_USER: mobility_user
      POSTGRES_PASSWORD: mobility_pass
      POSTGRES_DB: mobility_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mobility-network

  traffic-info-service:
    build:
      context: ./traffic-info-service
      dockerfile: Dockerfile
    container_name: traffic-info-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mobility_db
      - SPRING_DATASOURCE_USERNAME=mobility_user
      - SPRING_DATASOURCE_PASSWORD=mobility_pass
    depends_on:
      - postgres
    networks:
      - mobility-network

  mobility-recommendation-service:
    build:
      context: ./mobility-recommendation-service
      dockerfile: Dockerfile
    container_name: mobility-recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mobility_db
      - SPRING_DATASOURCE_USERNAME=mobility_user
      - SPRING_DATASOURCE_PASSWORD=mobility_pass
      - TRAFFIC_INFO_SERVICE_URL=http://traffic-info-service:8080
    depends_on:
      - postgres
      - traffic-info-service
    networks:
      - mobility-network

volumes:
  postgres_data:

networks:
  mobility-network:
    driver: bridge