apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: mobility_user
        - name: POSTGRES_PASSWORD
          value: mobility_pass
        - name: POSTGRES_DB
          value: mobility_db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS traffic_info (
        id SERIAL PRIMARY KEY,
        zip_code VARCHAR(8) NOT NULL,
        congestion_level INTEGER NOT NULL,
        timestamp TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mobility_recommendation (
        id SERIAL PRIMARY KEY,
        zip_code VARCHAR(8) NOT NULL,
        recommended_mode VARCHAR(50) NOT NULL,
        timestamp TIMESTAMP NOT NULL
    );
    